Nxengine
termux/x11-packages pull request #379
Opened 2021-07-06 12:26 UTC by Yonle

2021-07-06 12:30 UTC, WMCB-Tech requested changes
~~use `@TERMUX_PREFIX@` instead of `$PREFIX`~~

~~commit:
https://github.com/termux/x11-packages/pull/379/commits/911edf70a97710446c132946c373ee6a27d5330a~~

Have you done this, cuz i saw your commits using `$PREFIX` instead of `@TERMUX_PREFIX` in your patchfile

2021-07-06 12:39 UTC, Yonle commented
# GOD
WHAT THE HELL JUST HAPPEND, THIS IS NOT READY YET. DID I MISSCLICK!?

2021-07-06 12:39 UTC, closed without merging

2021-07-06 12:42 UTC, Yonle commented
Since i'm not sure, This may be complete. 

So sorry about this. This is really a mistake.

2021-07-06 12:47 UTC, xeffyr requested changes
Way to go.
* https://github.com/termux/termux-packages/wiki/Coding-guideline
* https://github.com/termux/termux-packages/wiki/Creating-new-package#writing-a-package-script

2021-07-06 12:47 UTC, xeffyr commented on packages/nxengine/build.sh
> +TERMUX_PKG_DESCRIPTION="Open-source rewrite engine of the Cave Story for Dingux and MotoMAGX. Author - Caitlin Shaw (rogueeve), httpd://nxengine.sourceforge.net"
No **long** descriptions. Keep description short, but informative. There no need to keep author and homepage in description, btw the latter one is stored in a separate field `TERMUX_PKG_HOMEPAGE`.

2021-07-06 12:47 UTC, xeffyr commented on packages/nxengine/build.sh
> +TERMUX_PKG_REVISION=4
Why revision starts from 4? This is a new package and therefore it shouldn't have revision field set. Revision is a build number and incremented each time when package should be rebuilt.

2021-07-06 12:47 UTC, xeffyr commented on packages/nxengine/build.sh
> +TERMUX_PKG_SRCURL=https://github.com/EXL/NXEngine/archive/refs/tags/v1.0.0.4-Rev4.tar.gz
Why version is hardcoded in srcurl? Reference it from `TERMUX_PKG_VERSION`.

2021-07-06 12:47 UTC, xeffyr commented on packages/nxengine/fix-prefix.patch
> ++LFLAGS        = -Wl,-O1 -Wl,-rpath,$TERMUX_PREFIX/lib
Why not to just use flags from LDFLAGS? Similar issue with INCPATH...

2021-07-06 12:47 UTC, xeffyr commented on packages/nxengine/fix-prefix.patch
> ++LIBS_STATIC   = $TERMUX_PREFIX/local/lib/libSDLmain.a $TERMUX_PREFIX/local/lib/libSDL.a $TERMUX_PREFIX/local/lib/libSDL_ttf.a -ldl -lpthread -lfreetype
Why there is a `/local` path component? Remove it. It is not supported officially and shouldn't be used in any of our packages.

If you need it for personal purposes, keep such changes in your fork instead.

2021-07-06 12:49 UTC, xeffyr commented
if you will want to re-submit a PR, please check the issues I've pointed in review comments.

2021-07-06 12:50 UTC, xeffyr commented on packages/nxengine/fix-prefix.patch
> ++LFLAGS        = -Wl,-O1 -Wl,-rpath,$TERMUX_PREFIX/lib
P.S. Compilers and other related vars should be retrieved from environment variables too.

2021-07-10 10:41 UTC, Yonle commented
By the way, I'm gonna resubmit the PR later. I may need to fix the building issue so i should fix it in my fork. Once i finish it, Gonna re-submit PR again. 

Also thanks for the issues. I'm gonna fix that sooner in next PR.