add package: arqiver
termux/x11-packages pull request #397
Opened 2021-07-27 13:34 UTC by Yisus7u7

![Screenshot_20210727-083407](https://user-images.githubusercontent.com/64093255/127163024-ee46cfeb-fb1c-4dad-9c2a-6eb215a4c76b.png)

2021-07-27 13:46 UTC, suhan-paradkar requested changes

2021-07-27 13:46 UTC, suhan-paradkar commented on packages/arqiver/build.sh
> +TERMUX_PKG_SRCURL=https://github.com/tsujan/Arqiver/archive/refs/tags/V{TERMUX_PKG_VERSION}.tar.gz
It must be `${TERMUX_PKG_VERSION}`

2021-07-27 13:47 UTC, Yisus7u7 commented on packages/arqiver/build.sh
> +TERMUX_PKG_SRCURL=https://github.com/tsujan/Arqiver/archive/refs/tags/V{TERMUX_PKG_VERSION}.tar.gz
Yes

2021-07-28 19:27 UTC, xeffyr approved these changes

2021-07-28 19:27 UTC, merged