add package: feathernotes
termux/x11-packages pull request #400
Opened 2021-07-28 23:19 UTC by Yisus7u7

![Screenshot_20210728-180343](https://user-images.githubusercontent.com/64093255/127408403-faa19408-8929-4547-86b7-062105e35c74.png)

2021-07-29 00:38 UTC, Yisus7u7 commented
@xeffyr

```
/home/builder/.termux-build/feathernotes/src/feathernotes/fn.cpp:2907:43: error: no member named 'families' in 'QFont'
        defaultFont_.setFamilies (newFont.families()); // to override the existing font families
                                  ~~~~~~~ ^
/home/builder/.termux-build/feathernotes/src/feathernotes/fn.cpp:2907:22: error: no member named 'setFamilies' in 'QFont'; did you mean 'setFamily'?
        defaultFont_.setFamilies (newFont.families()); // to override the existing font families
                     ^~~~~~~~~~~
                     setFamily
/data/data/com.termux/files/usr/include/QtGui/qfont.h:180:10: note: 'setFamily' declared here
    void setFamily(const QString &);
         ^
2 errors generated.
[40/52] Building CXX object feathernotes/CMakeFiles/feathernotes.dir/find.cpp.o
ninja: build stopped: subcommand failed.
Error: Process completed with exit code 1. ```

It's a very rare mistake, why?

2021-07-29 07:29 UTC, xeffyr commented
Maybe our Qt is just too old, we use `5.12` where 5.15 is out...

2021-07-29 16:20 UTC, Yisus7u7 commented
> Maybe our Qt is just too old, we use `5.12` where 5.15 is out...

Then I'll look forward to the qt update

2021-08-04 15:41 UTC, Yisus7u7 commented
I will use the direct version of git, this will be a temporary solution while termux updates Qt

2021-08-04 19:34 UTC, xeffyr requested changes

2021-08-04 19:34 UTC, xeffyr commented on packages/feathernotes/build.sh
> +TERMUX_PKG_SRCURL=https://github.com/Yisus7u7/shpkg-builds/releases/download/${TERMUX_PKG_VERSION}/feathernotes-${TERMUX_PKG_VERSION}.tar.xz
Custom sources aren't allowed. If you have made any changes to the source code, bundle patches within directory where build.sh is stored and set TERMUX_PKG_SRCURL to the original upstream.

2021-08-04 19:35 UTC, xeffyr commented
> I will use the direct version of git,

If it works with the latest git version, then issue is not "outdated Qt".

2021-08-04 19:36 UTC, Yisus7u7 commented
> > Usaré la versión directa de git,
> 
> Si funciona con la última versión de git, entonces el problema no es "Qt desactualizado".

Compile feathernotes directly Clone the git repository, it works, but using version release doesn't work

2021-08-04 19:37 UTC, Yisus7u7 commented
I didn't and added patches, they wouldn't do them, nor did they modify the source code, just the direct version of git

2021-08-04 19:40 UTC, xeffyr commented
**Use original URL!**

You don't need to manually fetch and store git sources somewhere else. TERMUX_PKG_SRCURL may contain URL to the repository managed by original author or fork managed by community.

2021-08-04 19:40 UTC, Yisus7u7 commented
Then it's time to patch, compare the git code with the one in the releases, how do you make a patch?

2021-08-04 19:41 UTC, xeffyr commented
https://github.com/tsujan/FeatherNotes/archive/087f522d62deed421b40d8fe96d66ecef0f38bf3.zip

...

2021-08-04 19:42 UTC, Yisus7u7 commented
> https://github.com/tsujan/FeatherNotes/archive/087f522d62deed421b40d8fe96d66ecef0f38bf3.zip
> 
> ...

That's the last commit  to the git repository?

2021-08-04 19:43 UTC, xeffyr commented
Yes, it is: https://github.com/tsujan/FeatherNotes/commit/087f522d62deed421b40d8fe96d66ecef0f38bf3. Latest commit on master branch.

2021-08-04 19:55 UTC, xeffyr commented
I have asked you to change only TERMUX_PKG_SRCURL. Does that mean to change version as well?

***

See an example of how it should look like:
https://github.com/termux/termux-packages/blob/79ed512695309db6d4bc2bec15ce9cc281ab7f66/packages/proot/build.sh#L6-L10

2021-08-04 20:40 UTC, xeffyr approved these changes

2021-08-04 20:40 UTC, merged