[add package]: tilda
termux/x11-packages pull request #439
Opened 2021-09-25 05:43 UTC by ELWAER-M

2021-09-26 08:32 UTC, xeffyr requested changes

2021-09-26 08:32 UTC, xeffyr commented on packages/tilda/build.sh
> +	./autogen.sh --prefix=$TERMUX_PREFIX
`NOCONFIGURE=1 ./autogen.sh`

2021-09-26 18:58 UTC, Yisus7u7 commented
@ELWAER-M You should not close this until it merges.

2021-09-26 19:34 UTC, xeffyr requested changes

2021-09-26 19:34 UTC, xeffyr commented on packages/tilda/build.sh
> +TERMUX_PKG_DEPENDS="glib, gtk3, libvte, libconfuse, libx11, gettext, automake, autoconf"
Remove gettext, automake and autoconf. They are not needed as runtime dependencies and not used during build time. Packages are cross-compiled and build tools installed in Termux prefix are not used and can't be anyway.

2021-09-26 19:34 UTC, xeffyr commented on packages/tilda/build.sh
> +TERMUX_PKG_EXTRA_MAKE_ARGS="--silent"
Why passing `--silent` to make? There no reason to make build logs shorter. They are intended to be informative.

2021-09-26 19:45 UTC, xeffyr requested changes

2021-09-26 19:45 UTC, xeffyr commented on packages/tilda/build.sh
> +    NOCONFIFURE=1 ./autogen.sh
Typo there. Should be `NOCONFIGURE=1 ./autogen.sh`, i.e. not `NOCONFIFURE=1 ...`.

2021-09-26 19:54 UTC, xeffyr commented on packages/tilda/build.sh
> +TERMUX_PKG_DEPENDS="glib, gtk3, libvte, libconfuse, libx11, gettext, automake, autoconf"
Well, gettext maybe still necessary.

2021-09-26 19:55 UTC, xeffyr commented
There few more issues than mentioned in review:
1. Need `TERMUX_PKG_BUILD_IN_SRC=true`
2. Compilation error:
```
src/tilda.c:57:10: fatal error: 'sys/dir.h' file not found
#include <sys/dir.h>
```

2021-09-26 23:28 UTC, xeffyr requested changes
As I have already mentioned, there is a compilation error (missing header) which needs a fix:
```
  CC       src/tilda-key_grabber.o
  CC       src/tilda-screen-size.o
  CC       src/tilda-tilda.o
  CC       src/tilda-tilda-keybinding.o
src/tilda.c:57:10: fatal error: 'sys/dir.h' file not found
#include <sys/dir.h>
         ^~~~~~~~~~~
1 error generated.
src/tilda-keybinding.c:306:43: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
                                          _ ("Enter keyboard shortcut"));
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/data/com.termux/files/usr/include/glib-2.0/glib/gi18n.h:26:20: note: expanded from macro '_'
#define  _(String) gettext (String)
```

2021-09-27 09:51 UTC, ELWAER-M commented
just forget that

2021-09-27 09:51 UTC, closed without merging