Create build.sh
termux/x11-packages pull request #493
Opened 2021-11-09 21:25 UTC by AnGelXoG

Gnuboy emulator

2021-11-12 06:11 UTC, AnGelXoG commented
finish code... xd

2021-11-12 21:24 UTC, xeffyr requested changes

2021-11-12 21:24 UTC, xeffyr commented on packages/gnuboy/makefile.patch
> +.PHONY: clean
This doesn't seem to be a valid patch file. Strongly recommending to create it with `diff` utility, especially if you don't know format internals.

2021-11-13 09:47 UTC, xeffyr requested changes
Properly create the patch file.

1. Take the original sources and extract them
2. Copy: `cp -a sources.orig sources.mod`
3. `cd sources.mod`
4. Make changes
5. `cd ..`
6. Create patch file: `diff -uNr sources.orig sources.mod > patchfile.patch`

2021-11-20 09:01 UTC, xeffyr commented
And still after a brief walkthrough about how to create patch, I don't see any progress and same mistakes as were before...
> Applying patch: makefile.patch
patch: **** unexpected end of file in patch

2021-11-20 09:01 UTC, closed without merging