Add missing dependencies for parole
termux/x11-packages pull request #503
Opened 2021-11-22 04:49 UTC by Yisus7u7

2021-11-22 22:46 UTC, xeffyr requested changes

2021-11-22 22:46 UTC, xeffyr commented on packages/gst-libav/build.sh
> +TERMUX_PKG_HOMEPAGE=https://gstreamer.freedesktop.org/modules/gst-libav.html
Move this to main repo.

2021-11-22 22:46 UTC, xeffyr commented on packages/parole/build.sh
>  TERMUX_PKG_SRCURL=http://deb.debian.org/debian/pool/main/p/parole/parole_${TERMUX_PKG_VERSION}.orig.tar.bz2
Need to bump revision. *[CONTRIBUTING.md](https://github.com/termux/x11-packages/blob/master/CONTRIBUTING.md#rebuilding-package-with-no-version-change) already tells us to bump revision when rebuilding package, isn't it?*

2021-11-23 02:11 UTC, Yisus7u7 commented
@xeffyr  You can now merge these two commitments

https://github.com/termux/termux-packages/pull/8044

2021-11-24 22:40 UTC, merged