add some packages for xfce4-goodies
termux/x11-packages pull request #504
Opened 2021-11-22 07:44 UTC by Yisus7u7

do not merge the changes yet, I will add more packages every time I have time and when I finish I will let you know.

2021-11-22 17:47 UTC, Yisus7u7 commented
@xeffyr 
the error is not mine, it is from the compiler.
```bash
termux - building xfce4-goodies for arch aarch64...
/home/builder/termux-packages/scripts/build/termux_step_create_debian_package.sh: line 49: AR: unbound variable
Error: Process completed with exit code 1.
```

2021-11-22 18:07 UTC, Yisus7u7 commented
![Screenshot_20211122-130542](https://user-images.githubusercontent.com/64093255/142912856-d40cc5b9-8546-427a-8fd2-4a383154a676.png)

2021-11-23 02:44 UTC, Yisus7u7 commented
@xeffyr You can now merge the changes.

Actual state:
- Added a large part of xfce4-goodies
- Unable to create xfce4-goodies meta package due to a bug in termux_step_create_debian_package.sh
- file-roller fails during "ninja install"
- it is recommended to disable the xarchiver package as it is useless, it does not work.
- xfce4-screenshot has a rare error with help2man, this does not happen on the device.

*Disabled packages*
- file-roller
- xfce4-goodies
- xfce4-screenshoter
- libdbusmenu-gtk3

2021-11-23 02:46 UTC, Yisus7u7 commented
I'm very exhausted, I hope this helps

2021-11-24 22:46 UTC, xeffyr requested changes

2021-11-24 22:46 UTC, xeffyr commented on disabled-packages/libdbusmenu-gtk3/build.sh
> +	export PATH=$PATH:$TERMUX_PREFIX/bin
Don't use `$TERMUX_PREFIX/bin`. You can't use cross-compiled tools in builder image.

2021-11-24 22:46 UTC, xeffyr commented on disabled-packages/xfce4-goodies/build.sh
> +TERMUX_PKG_PROVIDES="xfce4-plugins"
Package conflicts with itself, replaces and provides itself? Are you sure that these fields should be set for the newly added package?

2021-11-24 23:09 UTC, Yisus7u7 commented
@xeffyr You can now merge the changes.

2021-11-28 17:01 UTC, merged

2021-12-01 14:04 UTC, Yisus7u7 commented
> when can we download this? thanks for the good work

just search for the name of the plugin you need and install it with pkg

2021-12-01 14:05 UTC, Yisus7u7 commented
Or run:

`pkg install xfce4-*`