fix cairo-dock libs
termux/x11-packages pull request #514
Opened 2021-12-04 02:57 UTC by Yisus7u7

2021-12-04 09:28 UTC, xeffyr requested changes

2021-12-04 09:28 UTC, xeffyr commented on packages/cairo-dock-core/build.sh
> +
Please get rid of multilib sets. Termux doesn't support this. We also do not recommend using `LD_LIBRARY_PATH` anymore - it breaks stuff that uses Android libraries such as OpenSLES. All libraries **must** be installed into `$TERMUX_PREFIX/lib`. And don't set executable bit on libraries, especially from postinst script.

Termux file system layour: https://github.com/termux/termux-packages/wiki/Termux-file-system-layout

2021-12-04 13:07 UTC, Yisus7u7 commented
@xeffyr Done, works fine.

2021-12-04 16:32 UTC, xeffyr commented
> Done, works fine.

Not done. You need to get rid of `lib32` / `lib64`.

2021-12-04 16:36 UTC, Yisus7u7 commented
> > Done, works fine.
> 
> Not done. You need to get rid of `lib32` / `lib64`. Package source or build config should be modified to install binaries to `$TERMUX_PREFIX/lib`.

cairo-dock compulsorily uses these routes, it is even in the documentation of its official website

2021-12-04 16:36 UTC, Yisus7u7 commented
if you analyze the packages of other distro they respect this

2021-12-04 16:39 UTC, Yisus7u7 commented
@xeffyr 

https://glx-dock.org/ww_page.php?p=By%20compiling&lang=en

2021-12-04 22:36 UTC, Grimler91 commented
> if you analyze the packages of other distro they respect this

Well, we (as in termux) don't, installing 32bit packages on 64bit arches isn't supported, so there's no reason to split it into lib{32,64}

2021-12-04 22:40 UTC, Yisus7u7 commented
> > if you analyze the packages of other distro they respect this
> 
> Well, we (as in termux) don't, installing 32bit packages on 64bit arches isn't supported, so there's no reason to split it into lib{32,64}

2021-12-05 07:53 UTC, Grimler91 commented
> He did not understand me.
> 
> lib32 libraries will go on 32-bit devices, while 64-bit libraries will go on 64-bit devices, there are no lib32 libraries on 64-bit devices and vice versa

Yes, I can see that from the code. Are you suggesting that the libraries in all other packages should be moved to lib{32,64} as well? 

If not, then cairo-dock would be the only one out of 1000 packages that uses lib{32,64}. What makes cairo-dock special in this regard? 

If yes, then we would have to rebuild all packages and update all RPATHs. What would we gain from all this extra work?

2021-12-05 09:32 UTC, xeffyr commented
> He did not understand me.

That's you do not understand me.

Termux doesn't create library directories `lib32` or `lib64`, i.e. directories specific to 32/64 bits. It uses `lib` instead, which will have 64 bit libraries in 64 bit devices and 32 bit on 32 bit devices. You shouldn't take care about placing library somewhere manually.

However if package makes `lib32` and `lib64`, that behavior must be patched to install library files directly to `$TERMUX_PREFIX/lib`.

Also: my availability is limited and therefore *I kindly request to submit changes that are complete, have reasonable quality and match Termux design* (https://wiki.termux.com/wiki/Differences_from_Linux). If package needs to be patched,then make patch. Pull request that do not implement requested changes will be closed.

> If not, then cairo-dock would be the only one out of 1000 packages that uses lib{32,64}. What makes cairo-dock special in this regard?

I remember there is (or was) a package that did same and was successfully patched to avoid installation to `lib64` or `lib32`. These directories are for multilib compatibility only. Termux doesn't support multilib for now.

2021-12-05 09:35 UTC, xeffyr commented
Fixable by `-DLIB_SUFFIX=` as said in INSTALL file.

2021-12-05 09:35 UTC, closed without merging

2021-12-05 09:43 UTC, xeffyr commented
https://github.com/termux/x11-packages/commit/3500307822d756d8f1e1854dbfe77c123d5f068d

2021-12-05 12:52 UTC, Yisus7u7 commented
Oh ok, thanks!